### PR TITLE
Added Zooming and adjusted distances between clusters

### PR DESCRIPTION
**Pull request by Dara2004**
image

### CODE REVIEW

**Comment by Dara2004** [comment]
close #41

**Comment by MayKikuchi** [comment]
which project are you using btw? I'm using the testJavaProject and am getting:

image

also is Main supposed to have import lines?

**Comment by ZhiHanL** [comment]
I noticed that the island re-renders and changes image when you zoom in and out, is there an easy fix to this?

**Comment by Dara2004** [comment]
> which project are you using btw? I'm using the testJavaProject and am getting:
> 
> image
> 
> also is Main supposed to have import lines?

I used tinyDotStarter-evaluationCompleted. nothing going in/out of Main is a bug. I just let John know!

**Comment by Dara2004** [comment]
> I noticed that the island re-renders and changes image when you zoom in and out or pan around, is there an easy fix to this?

Are you sure the islands still rerendered? I had a previous commit to fix that so the islands don't re-render anymore as far as I can tell

**Comment by MayKikuchi** [comment]
> > I noticed that the island re-renders and changes image when you zoom in and out or pan around, is there an easy fix to this?
> 
> Are you sure the islands still rerendered? I had a previous commit to fix that so the islands don't re-render anymore as far as I can tell

just chiming in: I'm not getting the rerendering issue either 🤷

**Comment by ZhiHanL** [comment]
Oh yeah, ignore me, I was on an outdated version

**Pull request merged**
